const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  ASSET_MANAGER: 'ASSET_MANAGER',
  DEPARTMENT_HEAD: 'DEPARTMENT_HEAD',
  EMPLOYEE: 'EMPLOYEE',
};

const ASSET_STATUS = {
  AVAILABLE: 'AVAILABLE',
  ALLOCATED: 'ALLOCATED',
  RESERVED: 'RESERVED',
  UNDER_MAINTENANCE: 'UNDER_MAINTENANCE',
  LOST: 'LOST',
  RETIRED: 'RETIRED',
  DISPOSED: 'DISPOSED',
};

const ALLOCATION_STATUS = {
  ACTIVE: 'ACTIVE',
  RETURNED: 'RETURNED'
};

const BOOKING_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  COMPLETED: 'COMPLETED'
};

const MAINTENANCE_STATUS = {
  SCHEDULED: 'SCHEDULED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED'
};

const AUDIT_STATUS = {
  VERIFIED: 'VERIFIED',
  MISSING: 'MISSING',
  DAMAGED: 'DAMAGED'
};

const NOTIFICATION_TYPE = {
  INFO: 'INFO',
  WARNING: 'WARNING',
  ALERT: 'ALERT'
};

module.exports = {
  ROLES,
  ASSET_STATUS,
  ALLOCATION_STATUS,
  BOOKING_STATUS,
  MAINTENANCE_STATUS,
  AUDIT_STATUS,
  NOTIFICATION_TYPE
};
