import React from 'react';
import PropTypes from 'prop-types';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import Input from '../common/Input';
import Button from '../common/Button';
import { LIFECYCLE_STATUS_OPTIONS, CONDITION_OPTIONS } from '../../constants/asset.constants';

// Zod Validation Schema
const schema = z.object({
  name: z
    .string()
    .min(1, 'Asset Name is required')
    .max(100, 'Name must be 100 characters or less'),
  category_id: z.string().min(1, 'Category is required'),
  asset_tag: z.string().optional().or(z.literal('')),
  serial_number: z.string().max(100, 'Serial number must be 100 characters or less').optional().or(z.literal('')),
  acquisition_date: z.string().min(1, 'Acquisition Date is required'),
  acquisition_cost: z
    .union([
      z.string().transform((val) => (val === '' ? null : Number(val))),
      z.number(),
      z.null(),
    ])
    .refine((val) => val === null || (!isNaN(val) && val >= 0), {
      message: 'Acquisition Cost must be a positive number',
    }),
  condition: z.string().min(1, 'Condition is required'),
  location: z.string().min(1, 'Location is required'),
  department_id: z.string().optional().or(z.literal('')),
  is_bookable: z.boolean().default(false),
  status: z.string().min(1, 'Lifecycle Status is required'),
});

/**
 * AssetForm Component
 *
 * @component
 * @param {Object} props
 * @param {Object} [props.initialData] - Existing asset fields (if editing)
 * @param {Array<Object>} props.categories - Categories from backend
 * @param {Array<Object>} props.departments - Departments from backend
 * @param {Function} props.onSubmit - Callback on submit
 * @param {Function} props.onCancel - Callback on cancel
 * @param {boolean} [props.loading] - Submission state indicator
 */
export default function AssetForm({
  initialData = null,
  categories = [],
  departments = [],
  onSubmit,
  onCancel,
  loading = false,
}) {
  const {
    register,
    handleSubmit,
    setValue,
    watch,
    formState: { errors },
  } = useForm({
    resolver: zodResolver(schema),
    defaultValues: {
      name: initialData?.name || '',
      category_id: initialData?.category_id || initialData?.category?.id || '',
      asset_tag: initialData?.asset_tag || '',
      serial_number: initialData?.serial_number || '',
      acquisition_date: initialData?.acquisition_date
        ? new Date(initialData.acquisition_date).toISOString().split('T')[0]
        : '',
      acquisition_cost: initialData?.acquisition_cost != null ? String(initialData.acquisition_cost) : '',
      condition: initialData?.condition || 'good',
      location: initialData?.location_name || initialData?.location?.name || initialData?.location || '',
      department_id: initialData?.department_id || initialData?.department?.id || '',
      is_bookable: initialData?.is_bookable || false,
      status: initialData?.status || 'available',
    },
  });

  const isBookable = watch('is_bookable');

  // Handle local file selections before passing data up
  const handleFormSubmit = (data) => {
    const photoInput = document.getElementById('photo-upload');
    const docInput = document.getElementById('doc-upload');

    const payload = {
      ...data,
      photoFile: photoInput?.files?.[0] || null,
      docFile: docInput?.files?.[0] || null,
    };

    onSubmit(payload);
  };

  return (
    <form onSubmit={handleSubmit(handleFormSubmit)} className="space-y-6 text-left max-w-4xl mx-auto bg-white p-6 rounded-2xl border border-slate-200 shadow-sm">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Name */}
        <Input
          label="Asset Name"
          required
          placeholder="e.g. Dell Latitude 5420 Laptop"
          errorMessage={errors.name?.message}
          disabled={loading}
          {...register('name')}
        />

        {/* Asset Tag (readonly if editing/generated by backend) */}
        <Input
          label="Asset Tag"
          placeholder={initialData ? "" : "Leave blank for auto-generation"}
          readOnly={!!initialData}
          helperText={initialData ? "Asset Tag cannot be changed after creation." : "Leave empty if backend generates tags."}
          errorMessage={errors.asset_tag?.message}
          disabled={loading}
          {...register('asset_tag')}
        />

        {/* Category */}
        <div className="flex flex-col space-y-1.5">
          <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider select-none">
            Asset Category <span className="text-rose-500 font-bold ml-1">*</span>
          </label>
          <select
            disabled={loading}
            className="w-full px-4 py-2.5 bg-slate-50 border border-slate-200 text-slate-800 rounded-xl text-sm focus:outline-none focus:bg-white focus:ring-2 focus:ring-indigo-500/20 disabled:bg-slate-100 disabled:text-slate-400"
            {...register('category_id')}
          >
            <option value="">Select Category</option>
            {categories.map((cat) => (
              <option key={cat.id} value={cat.id}>
                {cat.name}
              </option>
            ))}
          </select>
          {errors.category_id && (
            <p className="text-xs font-semibold text-rose-500">{errors.category_id.message}</p>
          )}
        </div>

        {/* Serial Number */}
        <Input
          label="Serial Number"
          placeholder="e.g. SN-9827364-X"
          errorMessage={errors.serial_number?.message}
          disabled={loading}
          {...register('serial_number')}
        />

        {/* Acquisition Date */}
        <Input
          label="Acquisition Date"
          type="date"
          required
          errorMessage={errors.acquisition_date?.message}
          disabled={loading}
          {...register('acquisition_date')}
        />

        {/* Acquisition Cost */}
        <Input
          label="Acquisition Cost"
          type="number"
          step="0.01"
          placeholder="e.g. 1200.00"
          errorMessage={errors.acquisition_cost?.message}
          disabled={loading}
          {...register('acquisition_cost')}
        />

        {/* Condition */}
        <div className="flex flex-col space-y-1.5">
          <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider select-none">
            Condition <span className="text-rose-500 font-bold ml-1">*</span>
          </label>
          <select
            disabled={loading}
            className="w-full px-4 py-2.5 bg-slate-50 border border-slate-200 text-slate-800 rounded-xl text-sm focus:outline-none focus:bg-white focus:ring-2 focus:ring-indigo-500/20"
            {...register('condition')}
          >
            {CONDITION_OPTIONS.map((opt) => (
              <option key={opt.value} value={opt.value}>
                {opt.label}
              </option>
            ))}
          </select>
          {errors.condition && (
            <p className="text-xs font-semibold text-rose-500">{errors.condition.message}</p>
          )}
        </div>

        {/* Location */}
        <Input
          label="Current Location"
          required
          placeholder="e.g. Floor 3, Desk A8"
          errorMessage={errors.location?.message}
          disabled={loading}
          {...register('location')}
        />

        {/* Department */}
        <div className="flex flex-col space-y-1.5">
          <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider select-none">
            Assigned Department
          </label>
          <select
            disabled={loading}
            className="w-full px-4 py-2.5 bg-slate-50 border border-slate-200 text-slate-800 rounded-xl text-sm focus:outline-none focus:bg-white focus:ring-2 focus:ring-indigo-500/20"
            {...register('department_id')}
          >
            <option value="">None / Floating</option>
            {departments.map((dept) => (
              <option key={dept.id} value={dept.id}>
                {dept.name}
              </option>
            ))}
          </select>
          {errors.department_id && (
            <p className="text-xs font-semibold text-rose-500">{errors.department_id.message}</p>
          )}
        </div>

        {/* Lifecycle Status */}
        <div className="flex flex-col space-y-1.5">
          <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider select-none">
            Lifecycle Status <span className="text-rose-500 font-bold ml-1">*</span>
          </label>
          <select
            disabled={loading}
            className="w-full px-4 py-2.5 bg-slate-50 border border-slate-200 text-slate-800 rounded-xl text-sm focus:outline-none focus:bg-white focus:ring-2 focus:ring-indigo-500/20"
            {...register('status')}
          >
            {LIFECYCLE_STATUS_OPTIONS.map((opt) => (
              <option key={opt.value} value={opt.value}>
                {opt.label}
              </option>
            ))}
          </select>
          {errors.status && (
            <p className="text-xs font-semibold text-rose-500">{errors.status.message}</p>
          )}
        </div>

        {/* Photo Upload */}
        <div className="flex flex-col space-y-1.5">
          <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider select-none">
            Upload Asset Photo
          </label>
          <input
            id="photo-upload"
            type="file"
            accept="image/*"
            disabled={loading}
            className="w-full px-3 py-2 bg-slate-55/10 border border-slate-200 text-slate-700 rounded-xl text-sm file:mr-4 file:py-1.5 file:px-3 file:rounded-lg file:border-0 file:text-xs file:font-semibold file:bg-indigo-50 file:text-indigo-700 hover:file:bg-indigo-100"
          />
        </div>

        {/* Document Upload */}
        <div className="flex flex-col space-y-1.5">
          <label className="block text-xs font-bold text-slate-550 uppercase tracking-wider select-none">
            Upload Manual / Invoice Document
          </label>
          <input
            id="doc-upload"
            type="file"
            accept=".pdf,.doc,.docx,.xls,.xlsx"
            disabled={loading}
            className="w-full px-3 py-2 bg-slate-55/10 border border-slate-200 text-slate-700 rounded-xl text-sm file:mr-4 file:py-1.5 file:px-3 file:rounded-lg file:border-0 file:text-xs file:font-semibold file:bg-indigo-50 file:text-indigo-700 hover:file:bg-indigo-100"
          />
        </div>

        {/* Bookable Toggle */}
        <div className="flex items-center space-x-3 pt-6">
          <input
            id="is_bookable"
            type="checkbox"
            disabled={loading}
            className="h-4 w-4 rounded border-slate-300 text-indigo-600 focus:ring-indigo-500 cursor-pointer"
            {...register('is_bookable')}
          />
          <label htmlFor="is_bookable" className="text-sm font-semibold text-slate-700 select-none cursor-pointer">
            This asset is Shared & Bookable by Employees
          </label>
        </div>
      </div>

      <div className="flex justify-end gap-3 pt-6 border-t border-slate-150">
        <Button variant="outline" onClick={onCancel} disabled={loading}>
          Cancel
        </Button>
        <Button type="submit" variant="primary" loading={loading}>
          {initialData ? 'Save Changes' : 'Register Asset'}
        </Button>
      </div>
    </form>
  );
}

AssetForm.propTypes = {
  initialData: PropTypes.shape({
    id: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
    name: PropTypes.string,
    category_id: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
    category: PropTypes.shape({ id: PropTypes.oneOfType([PropTypes.string, PropTypes.number]) }),
    asset_tag: PropTypes.string,
    serial_number: PropTypes.string,
    acquisition_date: PropTypes.string,
    acquisition_cost: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
    condition: PropTypes.string,
    location: PropTypes.oneOfType([
      PropTypes.string,
      PropTypes.shape({ name: PropTypes.string }),
    ]),
    location_name: PropTypes.string,
    department_id: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
    department: PropTypes.shape({ id: PropTypes.oneOfType([PropTypes.string, PropTypes.number]) }),
    is_bookable: PropTypes.bool,
    status: PropTypes.string,
  }),
  categories: PropTypes.arrayOf(
    PropTypes.shape({
      id: PropTypes.oneOfType([PropTypes.string, PropTypes.number]).isRequired,
      name: PropTypes.string.isRequired,
    })
  ),
  departments: PropTypes.arrayOf(
    PropTypes.shape({
      id: PropTypes.oneOfType([PropTypes.string, PropTypes.number]).isRequired,
      name: PropTypes.string.isRequired,
    })
  ),
  onSubmit: PropTypes.func.isRequired,
  onCancel: PropTypes.func.isRequired,
  loading: PropTypes.bool,
};
